import { useMutation, useQueryClient } from '@tanstack/react-query';
import { getCookie } from '@/lib/api';
import { sendMessage, type Conversation, type SendMessagePayload } from '../api/dmService';

/**
 * Hook to send a message in a conversation
 */
export const useSendMessage = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: sendMessage,
    onMutate: async (payload: SendMessagePayload) => {
      // Cancel outgoing queries for this conversation
      await queryClient.cancelQueries({ queryKey: ['conversation', payload.conversationId] });

      // Snapshot previous value
      const previousConversation = queryClient.getQueryData([
        'conversation',
        payload.conversationId,
      ]);

      // Get current user ID from cookies for optimistic update
      const currentUserId = getCookie('userId');

      // Optimistically add message to conversation (without _id since it's generated by backend)
      if (previousConversation && currentUserId) {
        queryClient.setQueryData(
          ['conversation', payload.conversationId],
          (old: Conversation | undefined) => {
            if (!old) return old;
            return {
              ...old,
              messages: [
                ...old.messages,
                {
                  senderId: currentUserId, // Use actual user ID so message appears on correct side
                  body: payload.body,
                  timestamp: new Date(),
                  readBy: [],
                },
              ],
            };
          }
        );
      }

      return { previousConversation };
    },
    onError: (_error, variables, context) => {
      // Rollback on error
      if (context?.previousConversation) {
        queryClient.setQueryData(
          ['conversation', variables.conversationId],
          context.previousConversation
        );
      }
      console.error('Failed to send message:', _error);
    },
    onSuccess: (_data, variables) => {
      // Invalidate conversation to refetch with real backend message
      queryClient.invalidateQueries({ queryKey: ['conversation', variables.conversationId] });
      queryClient.invalidateQueries({ queryKey: ['conversations'] });
    },
  });
};
